// ============================================================
// BRICS AI Governance Platform — Centralized Mock Data
// Replace calls to mockData with api.get...() when backend is ready
// ============================================================

import type {
  Complaint,
  Region,
  Hotspot,
  InfrastructureGap,
  Recommendation,
  GovernmentPlan,
  Analytics,
  DashboardOverview,
  CitizenDashboard,
  AreaData,
} from '@/types';

// ── Complaints ────────────────────────────────────────────────
export const mockComplaints: Complaint[] = [
  {
    id: 'CMP-2024-001',
    citizenId: 'CTZ-001',
    text: 'The primary healthcare centre in our village has been closed for 3 months. Patients have to travel over 40 km for basic treatment.',
    originalLanguage: 'Hindi',
    translatedText: 'The primary healthcare centre in our village has been closed for 3 months. Patients have to travel over 40 km for basic treatment.',
    category: 'Healthcare',
    severity: 9,
    priority: 'critical',
    status: 'in_progress',
    location: { lat: 25.5941, lng: 85.1376, region: 'Patna', district: 'Patna', country: 'India' },
    aiClassification: 'Healthcare Access - Critical',
    aiConfidence: 0.94,
    createdAt: '2024-11-10T08:00:00Z',
    updatedAt: '2024-11-15T12:00:00Z',
    timeline: [
      { stage: 'submitted', label: 'Submitted', completedAt: '2024-11-10T08:00:00Z', completed: true },
      { stage: 'ai_classified', label: 'AI Classified', completedAt: '2024-11-10T08:02:00Z', note: 'Healthcare Access - Critical (94% confidence)', completed: true },
      { stage: 'under_review', label: 'Under Review', completedAt: '2024-11-11T09:00:00Z', completed: true },
      { stage: 'assigned', label: 'Assigned', completedAt: '2024-11-12T10:00:00Z', note: 'Assigned to District Health Officer', completed: true },
      { stage: 'in_progress', label: 'In Progress', completedAt: '2024-11-15T12:00:00Z', completed: true },
      { stage: 'resolved', label: 'Resolved', completed: false },
    ],
  },
  {
    id: 'CMP-2024-002',
    citizenId: 'CTZ-001',
    text: 'The main road connecting Rajpur to the highway has not been repaired in 2 years. Multiple potholes causing accidents.',
    originalLanguage: 'English',
    category: 'Roads & Transport',
    severity: 7,
    priority: 'high',
    status: 'under_review',
    location: { lat: 25.6121, lng: 85.1580, region: 'Patna', district: 'Rajpur', country: 'India' },
    aiClassification: 'Road Infrastructure - High Priority',
    aiConfidence: 0.91,
    createdAt: '2024-11-05T10:30:00Z',
    updatedAt: '2024-11-12T16:00:00Z',
    timeline: [
      { stage: 'submitted', label: 'Submitted', completedAt: '2024-11-05T10:30:00Z', completed: true },
      { stage: 'ai_classified', label: 'AI Classified', completedAt: '2024-11-05T10:32:00Z', completed: true },
      { stage: 'under_review', label: 'Under Review', completedAt: '2024-11-12T16:00:00Z', completed: true },
      { stage: 'assigned', label: 'Assigned', completed: false },
      { stage: 'in_progress', label: 'In Progress', completed: false },
      { stage: 'resolved', label: 'Resolved', completed: false },
    ],
  },
  {
    id: 'CMP-2024-003',
    citizenId: 'CTZ-001',
    text: 'No piped water supply for 6 months. Residents depend on contaminated well water.',
    originalLanguage: 'English',
    category: 'Water & Sanitation',
    severity: 8,
    priority: 'high',
    status: 'submitted',
    location: { lat: 25.5800, lng: 85.1200, region: 'Patna', district: 'Patna', country: 'India' },
    aiClassification: 'Water Access - High Priority',
    aiConfidence: 0.88,
    createdAt: '2024-11-18T07:00:00Z',
    updatedAt: '2024-11-18T07:00:00Z',
    timeline: [
      { stage: 'submitted', label: 'Submitted', completedAt: '2024-11-18T07:00:00Z', completed: true },
      { stage: 'ai_classified', label: 'AI Classified', completed: false },
      { stage: 'under_review', label: 'Under Review', completed: false },
      { stage: 'assigned', label: 'Assigned', completed: false },
      { stage: 'in_progress', label: 'In Progress', completed: false },
      { stage: 'resolved', label: 'Resolved', completed: false },
    ],
  },
  {
    id: 'CMP-2024-004',
    citizenId: 'CTZ-002',
    text: 'Escola pública fechada há 2 semanas por falta de professores. 200 crianças sem aula.',
    originalLanguage: 'Portuguese',
    translatedText: 'Public school closed for 2 weeks due to lack of teachers. 200 children without classes.',
    category: 'Education',
    severity: 6,
    priority: 'medium',
    status: 'resolved',
    location: { lat: -23.5505, lng: -46.6333, region: 'São Paulo', district: 'Zona Norte', country: 'Brazil' },
    aiClassification: 'Education Access - Medium Priority',
    aiConfidence: 0.87,
    createdAt: '2024-10-20T09:00:00Z',
    updatedAt: '2024-11-01T14:00:00Z',
    resolvedAt: '2024-11-01T14:00:00Z',
    timeline: [
      { stage: 'submitted', label: 'Submitted', completedAt: '2024-10-20T09:00:00Z', completed: true },
      { stage: 'ai_classified', label: 'AI Classified', completedAt: '2024-10-20T09:03:00Z', completed: true },
      { stage: 'under_review', label: 'Under Review', completedAt: '2024-10-22T11:00:00Z', completed: true },
      { stage: 'assigned', label: 'Assigned', completedAt: '2024-10-24T09:00:00Z', completed: true },
      { stage: 'in_progress', label: 'In Progress', completedAt: '2024-10-26T09:00:00Z', completed: true },
      { stage: 'resolved', label: 'Resolved', completedAt: '2024-11-01T14:00:00Z', completed: true },
    ],
  },
  {
    id: 'CMP-2024-005',
    citizenId: 'CTZ-003',
    text: 'Нет интернета в деревне уже год. Дети не могут учиться дистанционно.',
    originalLanguage: 'Russian',
    translatedText: 'No internet in the village for a year. Children cannot study remotely.',
    category: 'Digital Connectivity',
    severity: 5,
    priority: 'medium',
    status: 'in_progress',
    location: { lat: 55.7558, lng: 37.6176, region: 'Moscow Oblast', district: 'Kolomna', country: 'Russia' },
    aiClassification: 'Digital Infrastructure - Medium Priority',
    aiConfidence: 0.82,
    createdAt: '2024-11-01T11:00:00Z',
    updatedAt: '2024-11-10T09:00:00Z',
    timeline: [
      { stage: 'submitted', label: 'Submitted', completedAt: '2024-11-01T11:00:00Z', completed: true },
      { stage: 'ai_classified', label: 'AI Classified', completedAt: '2024-11-01T11:02:00Z', completed: true },
      { stage: 'under_review', label: 'Under Review', completedAt: '2024-11-03T10:00:00Z', completed: true },
      { stage: 'assigned', label: 'Assigned', completedAt: '2024-11-05T09:00:00Z', completed: true },
      { stage: 'in_progress', label: 'In Progress', completedAt: '2024-11-10T09:00:00Z', completed: true },
      { stage: 'resolved', label: 'Resolved', completed: false },
    ],
  },
  {
    id: 'CMP-2024-006',
    citizenId: 'CTZ-001',
    text: 'Electricity supply disrupted for 12+ hours daily. Affecting livelihoods.',
    originalLanguage: 'English',
    category: 'Electricity',
    severity: 7,
    priority: 'high',
    status: 'submitted',
    location: { lat: 25.5900, lng: 85.1300, region: 'Patna', district: 'Patna', country: 'India' },
    aiClassification: 'Power Infrastructure - High Priority',
    aiConfidence: 0.90,
    createdAt: '2024-11-19T06:00:00Z',
    updatedAt: '2024-11-19T06:00:00Z',
    timeline: [
      { stage: 'submitted', label: 'Submitted', completedAt: '2024-11-19T06:00:00Z', completed: true },
      { stage: 'ai_classified', label: 'AI Classified', completedAt: '2024-11-19T06:02:00Z', completed: true },
      { stage: 'under_review', label: 'Under Review', completed: false },
      { stage: 'assigned', label: 'Assigned', completed: false },
      { stage: 'in_progress', label: 'In Progress', completed: false },
      { stage: 'resolved', label: 'Resolved', completed: false },
    ],
  },
];

// ── Regions ───────────────────────────────────────────────────
export const mockRegions: Region[] = [
  {
    id: 'REG-001',
    name: 'Bihar',
    country: 'India',
    population: 128500000,
    totalComplaints: 8420,
    resolvedComplaints: 3900,
    resolutionRate: 46,
    infrastructureScore: 28,
    satisfactionScore: 31,
    topIssue: 'Healthcare',
    coordinates: { lat: 25.0961, lng: 85.3131 },
    priority: 'critical',
  },
  {
    id: 'REG-002',
    name: 'Uttar Pradesh',
    country: 'India',
    population: 220000000,
    totalComplaints: 12100,
    resolvedComplaints: 5800,
    resolutionRate: 48,
    infrastructureScore: 34,
    satisfactionScore: 38,
    topIssue: 'Roads & Transport',
    coordinates: { lat: 26.8467, lng: 80.9462 },
    priority: 'critical',
  },
  {
    id: 'REG-003',
    name: 'Pará',
    country: 'Brazil',
    population: 8800000,
    totalComplaints: 3200,
    resolvedComplaints: 2100,
    resolutionRate: 66,
    infrastructureScore: 48,
    satisfactionScore: 54,
    topIssue: 'Water & Sanitation',
    coordinates: { lat: -3.7172, lng: -52.2271 },
    priority: 'high',
  },
  {
    id: 'REG-004',
    name: 'Maranhão',
    country: 'Brazil',
    population: 7200000,
    totalComplaints: 2800,
    resolvedComplaints: 1400,
    resolutionRate: 50,
    infrastructureScore: 40,
    satisfactionScore: 42,
    topIssue: 'Education',
    coordinates: { lat: -4.9609, lng: -45.2744 },
    priority: 'high',
  },
  {
    id: 'REG-005',
    name: 'Siberia',
    country: 'Russia',
    population: 19000000,
    totalComplaints: 1900,
    resolvedComplaints: 1500,
    resolutionRate: 79,
    infrastructureScore: 55,
    satisfactionScore: 61,
    topIssue: 'Digital Connectivity',
    coordinates: { lat: 61.5240, lng: 105.3188 },
    priority: 'medium',
  },
  {
    id: 'REG-006',
    name: 'Xinjiang',
    country: 'China',
    population: 25000000,
    totalComplaints: 2100,
    resolvedComplaints: 1700,
    resolutionRate: 81,
    infrastructureScore: 62,
    satisfactionScore: 68,
    topIssue: 'Roads & Transport',
    coordinates: { lat: 42.1254, lng: 87.1329 },
    priority: 'medium',
  },
  {
    id: 'REG-007',
    name: 'Eastern Cape',
    country: 'South Africa',
    population: 6800000,
    totalComplaints: 3500,
    resolvedComplaints: 1800,
    resolutionRate: 51,
    infrastructureScore: 44,
    satisfactionScore: 46,
    topIssue: 'Water & Sanitation',
    coordinates: { lat: -32.2968, lng: 26.4194 },
    priority: 'high',
  },
  {
    id: 'REG-008',
    name: 'Limpopo',
    country: 'South Africa',
    population: 5900000,
    totalComplaints: 3100,
    resolvedComplaints: 1300,
    resolutionRate: 42,
    infrastructureScore: 38,
    satisfactionScore: 40,
    topIssue: 'Healthcare',
    coordinates: { lat: -23.4013, lng: 29.4179 },
    priority: 'critical',
  },
];

// ── Hotspots ──────────────────────────────────────────────────
export const mockHotspots: Hotspot[] = [
  {
    id: 'HOT-001',
    regionId: 'REG-001',
    regionName: 'Bihar',
    country: 'India',
    coordinates: { lat: 25.5941, lng: 85.1376 },
    population: 12800000,
    complaintCount: 2840,
    topIssue: 'Healthcare',
    infrastructureGapScore: 91,
    demandScore: 92,
    populationImpactScore: 89,
    priorityScore: 91.2,
    priority: 'critical',
    aiRecommendation: 'Expand healthcare capacity in underserved population clusters. Priority deployment of mobile health units while permanent infrastructure is built.',
    categories: [
      { name: 'Healthcare', count: 1100 },
      { name: 'Roads', count: 720 },
      { name: 'Water', count: 580 },
      { name: 'Education', count: 440 },
    ],
  },
  {
    id: 'HOT-002',
    regionId: 'REG-002',
    regionName: 'Uttar Pradesh',
    country: 'India',
    coordinates: { lat: 26.8467, lng: 80.9462 },
    population: 22000000,
    complaintCount: 4200,
    topIssue: 'Roads & Transport',
    infrastructureGapScore: 84,
    demandScore: 88,
    populationImpactScore: 95,
    priorityScore: 88.6,
    priority: 'critical',
    aiRecommendation: 'Accelerate road maintenance and rural connectivity programs. High population density amplifies impact of transport infrastructure failures.',
    categories: [
      { name: 'Roads', count: 1600 },
      { name: 'Healthcare', count: 980 },
      { name: 'Education', count: 860 },
      { name: 'Water', count: 760 },
    ],
  },
  {
    id: 'HOT-003',
    regionId: 'REG-008',
    regionName: 'Limpopo',
    country: 'South Africa',
    coordinates: { lat: -23.4013, lng: 29.4179 },
    population: 5900000,
    complaintCount: 1800,
    topIssue: 'Healthcare',
    infrastructureGapScore: 82,
    demandScore: 79,
    populationImpactScore: 84,
    priorityScore: 82.1,
    priority: 'critical',
    aiRecommendation: 'Establish regional healthcare hubs with telemedicine capabilities to address critical shortfall in rural health services.',
    categories: [
      { name: 'Healthcare', count: 720 },
      { name: 'Water', count: 430 },
      { name: 'Roads', count: 380 },
      { name: 'Education', count: 270 },
    ],
  },
  {
    id: 'HOT-004',
    regionId: 'REG-003',
    regionName: 'Pará',
    country: 'Brazil',
    coordinates: { lat: -3.7172, lng: -52.2271 },
    population: 8800000,
    complaintCount: 1600,
    topIssue: 'Water & Sanitation',
    infrastructureGapScore: 76,
    demandScore: 74,
    populationImpactScore: 78,
    priorityScore: 76.1,
    priority: 'high',
    aiRecommendation: 'Invest in water treatment and sanitation infrastructure. Tropical disease risk is elevated due to lack of clean water access.',
    categories: [
      { name: 'Water', count: 680 },
      { name: 'Roads', count: 420 },
      { name: 'Healthcare', count: 320 },
      { name: 'Environment', count: 180 },
    ],
  },
  {
    id: 'HOT-005',
    regionId: 'REG-007',
    regionName: 'Eastern Cape',
    country: 'South Africa',
    coordinates: { lat: -32.2968, lng: 26.4194 },
    population: 6800000,
    complaintCount: 1900,
    topIssue: 'Water & Sanitation',
    infrastructureGapScore: 74,
    demandScore: 76,
    populationImpactScore: 72,
    priorityScore: 74.3,
    priority: 'high',
    aiRecommendation: 'Prioritize water infrastructure investment. Drought resilience planning needed alongside immediate supply improvements.',
    categories: [
      { name: 'Water', count: 780 },
      { name: 'Roads', count: 490 },
      { name: 'Healthcare', count: 380 },
      { name: 'Electricity', count: 250 },
    ],
  },
  {
    id: 'HOT-006',
    regionId: 'REG-004',
    regionName: 'Maranhão',
    country: 'Brazil',
    coordinates: { lat: -4.9609, lng: -45.2744 },
    population: 7200000,
    complaintCount: 1400,
    topIssue: 'Education',
    infrastructureGapScore: 68,
    demandScore: 70,
    populationImpactScore: 65,
    priorityScore: 68.2,
    priority: 'high',
    aiRecommendation: 'Increase teacher recruitment and school infrastructure investment. Educational gaps are compounding long-term economic inequality.',
    categories: [
      { name: 'Education', count: 580 },
      { name: 'Water', count: 360 },
      { name: 'Healthcare', count: 280 },
      { name: 'Roads', count: 180 },
    ],
  },
  {
    id: 'HOT-007',
    regionId: 'REG-005',
    regionName: 'Siberia',
    country: 'Russia',
    coordinates: { lat: 61.5240, lng: 105.3188 },
    population: 19000000,
    complaintCount: 800,
    topIssue: 'Digital Connectivity',
    infrastructureGapScore: 52,
    demandScore: 60,
    populationImpactScore: 55,
    priorityScore: 55.8,
    priority: 'medium',
    aiRecommendation: 'Deploy rural broadband expansion program leveraging satellite infrastructure for remote communities.',
    categories: [
      { name: 'Digital', count: 320 },
      { name: 'Roads', count: 240 },
      { name: 'Healthcare', count: 160 },
      { name: 'Electricity', count: 80 },
    ],
  },
  {
    id: 'HOT-008',
    regionId: 'REG-006',
    regionName: 'Xinjiang',
    country: 'China',
    coordinates: { lat: 42.1254, lng: 87.1329 },
    population: 25000000,
    complaintCount: 700,
    topIssue: 'Roads & Transport',
    infrastructureGapScore: 48,
    demandScore: 52,
    populationImpactScore: 58,
    priorityScore: 52.2,
    priority: 'medium',
    aiRecommendation: 'Continue road network expansion with priority to agricultural areas to reduce logistics costs and improve market access.',
    categories: [
      { name: 'Roads', count: 310 },
      { name: 'Agriculture', count: 200 },
      { name: 'Digital', count: 120 },
      { name: 'Healthcare', count: 70 },
    ],
  },
];

// ── Infrastructure Gaps ───────────────────────────────────────
export const mockInfrastructureGaps: InfrastructureGap[] = [
  {
    id: 'INFRA-001',
    category: 'Healthcare',
    icon: '🏥',
    regionId: 'REG-001',
    regionName: 'Bihar',
    country: 'India',
    gapScore: 91,
    citizenDemand: 94,
    existingInfrastructure: 18,
    populationImpact: 92,
    currentInvestment: 22,
    description: 'Critical shortage of primary health centers. Doctor-to-patient ratio 5x below national average.',
    affectedPopulation: 11200000,
  },
  {
    id: 'INFRA-002',
    category: 'Roads & Transport',
    icon: '🛣️',
    regionId: 'REG-002',
    regionName: 'Uttar Pradesh',
    country: 'India',
    gapScore: 78,
    citizenDemand: 88,
    existingInfrastructure: 42,
    populationImpact: 85,
    currentInvestment: 48,
    description: 'Rural road connectivity severely lacking. 60% of villages not connected to all-weather roads.',
    affectedPopulation: 18000000,
  },
  {
    id: 'INFRA-003',
    category: 'Water & Sanitation',
    icon: '💧',
    regionId: 'REG-007',
    regionName: 'Eastern Cape',
    country: 'South Africa',
    gapScore: 84,
    citizenDemand: 86,
    existingInfrastructure: 28,
    populationImpact: 80,
    currentInvestment: 34,
    description: 'Water treatment facilities insufficient. 40% of population relies on unpiped water sources.',
    affectedPopulation: 2720000,
  },
  {
    id: 'INFRA-004',
    category: 'Digital Connectivity',
    icon: '📡',
    regionId: 'REG-005',
    regionName: 'Siberia',
    country: 'Russia',
    gapScore: 69,
    citizenDemand: 72,
    existingInfrastructure: 38,
    populationImpact: 64,
    currentInvestment: 42,
    description: 'Broadband penetration 30% below national average in rural Siberian communities.',
    affectedPopulation: 5700000,
  },
  {
    id: 'INFRA-005',
    category: 'Education',
    icon: '🎓',
    regionId: 'REG-004',
    regionName: 'Maranhão',
    country: 'Brazil',
    gapScore: 73,
    citizenDemand: 78,
    existingInfrastructure: 34,
    populationImpact: 76,
    currentInvestment: 38,
    description: 'Teacher shortage and inadequate school facilities limiting educational outcomes.',
    affectedPopulation: 3240000,
  },
  {
    id: 'INFRA-006',
    category: 'Electricity',
    icon: '⚡',
    regionId: 'REG-008',
    regionName: 'Limpopo',
    country: 'South Africa',
    gapScore: 65,
    citizenDemand: 68,
    existingInfrastructure: 44,
    populationImpact: 62,
    currentInvestment: 50,
    description: 'Unreliable power supply in rural areas. Load shedding 8-12 hours daily in some districts.',
    affectedPopulation: 1770000,
  },
];

// ── Recommendations ───────────────────────────────────────────
export const mockRecommendations: Recommendation[] = [
  {
    id: 'REC-001',
    regionId: 'REG-001',
    regionName: 'Bihar',
    country: 'India',
    category: 'Healthcare',
    priority: 'critical',
    priorityScore: 91.2,
    title: 'Emergency Healthcare Infrastructure Expansion',
    evidence: [
      '8,420 healthcare complaints logged in Bihar in 90 days',
      'Healthcare infrastructure gap score: 91/100',
      '128.5M population with only 18% infrastructure coverage',
      'Nearest healthcare facility >40km for 34% of population',
      'Infant mortality rate 2.3x national average',
    ],
    recommendedAction: 'Immediately deploy 50 mobile health units. Fast-track construction of 120 primary health centers. Recruit 2,400 additional healthcare workers using emergency allocation. Implement telemedicine connectivity in all district hospitals within 6 months.',
    expectedImpact: 'Reduce average healthcare travel distance from 40km to <10km for 11M+ citizens. Projected 23% reduction in preventable deaths within 18 months.',
    estimatedCost: '₹4,200 Crore',
    timeframe: '6–18 months',
    confidence: 94,
    affectedPopulation: 11200000,
    aiGenerated: true,
    createdAt: '2024-11-19T00:00:00Z',
  },
  {
    id: 'REC-002',
    regionId: 'REG-002',
    regionName: 'Uttar Pradesh',
    country: 'India',
    category: 'Roads & Transport',
    priority: 'critical',
    priorityScore: 88.6,
    title: 'Rural Road Connectivity Accelerator Program',
    evidence: [
      '12,100 transport complaints in 90 days',
      '60% of villages lack all-weather road connectivity',
      '220M population with massive economic productivity loss',
      'Agricultural losses estimated at ₹800Cr annually due to poor connectivity',
    ],
    recommendedAction: 'Launch emergency rural road repair initiative targeting 8,000km of critical connections. Prioritize roads connecting agricultural regions to market hubs. Deploy prefabricated bridge solutions for seasonal disconnections.',
    expectedImpact: 'Connect 4.2M citizens to all-weather roads. Estimated 15% increase in agricultural income for affected regions.',
    estimatedCost: '₹9,600 Crore',
    timeframe: '12–24 months',
    confidence: 91,
    affectedPopulation: 18000000,
    aiGenerated: true,
    createdAt: '2024-11-19T00:00:00Z',
  },
  {
    id: 'REC-003',
    regionId: 'REG-008',
    regionName: 'Limpopo',
    country: 'South Africa',
    category: 'Healthcare',
    priority: 'critical',
    priorityScore: 82.1,
    title: 'Limpopo Rural Healthcare Hub Network',
    evidence: [
      '3,100 healthcare complaints from Limpopo',
      'Infrastructure gap score: 82/100',
      'Doctor-patient ratio: 1:8,200 (national avg 1:3,100)',
      'Only 38% population within 20km of health facility',
    ],
    recommendedAction: 'Establish 8 regional healthcare hubs with specialist services. Deploy telemedicine infrastructure linking rural clinics to urban hospitals. Introduce community health worker program targeting 500 villages.',
    expectedImpact: '2.4M citizens gain improved healthcare access. Maternal mortality projected to decrease 31% in 24 months.',
    estimatedCost: 'R3.8 Billion',
    timeframe: '12–30 months',
    confidence: 87,
    affectedPopulation: 2400000,
    aiGenerated: true,
    createdAt: '2024-11-19T00:00:00Z',
  },
  {
    id: 'REC-004',
    regionId: 'REG-007',
    regionName: 'Eastern Cape',
    country: 'South Africa',
    category: 'Water & Sanitation',
    priority: 'high',
    priorityScore: 74.3,
    title: 'Clean Water Access Initiative — Eastern Cape',
    evidence: [
      '3,500 water & sanitation complaints',
      '40% of population lacks piped water',
      'Waterborne disease incidents up 18% year-on-year',
      'Infrastructure gap score: 84/100',
    ],
    recommendedAction: 'Construct 12 regional water treatment plants. Extend piped water to 180 underserved communities. Implement drought-resilient rainwater harvesting systems. Upgrade 340km of aging water distribution infrastructure.',
    expectedImpact: '2.7M citizens gain access to clean piped water. Waterborne disease incidents projected to fall 45%.',
    estimatedCost: 'R2.1 Billion',
    timeframe: '18–36 months',
    confidence: 82,
    affectedPopulation: 2720000,
    aiGenerated: true,
    createdAt: '2024-11-19T00:00:00Z',
  },
  {
    id: 'REC-005',
    regionId: 'REG-003',
    regionName: 'Pará',
    country: 'Brazil',
    category: 'Water & Sanitation',
    priority: 'high',
    priorityScore: 76.1,
    title: 'Pará Amazon Basin Water Infrastructure Program',
    evidence: [
      '3,200 complaints from Pará region',
      'Sanitation coverage only 38% in rural areas',
      'Amazon pollution affecting water quality downstream',
    ],
    recommendedAction: 'Deploy portable water purification systems to 220 riverside communities. Build sanitation infrastructure targeting Amazon basin settlements. Establish water quality monitoring network.',
    expectedImpact: '1.8M citizens in rural Pará gain clean water access. Disease burden reduction estimated at 28%.',
    estimatedCost: 'R$1.4 Billion',
    timeframe: '12–24 months',
    confidence: 79,
    affectedPopulation: 1800000,
    aiGenerated: true,
    createdAt: '2024-11-19T00:00:00Z',
  },
  {
    id: 'REC-006',
    regionId: 'REG-005',
    regionName: 'Siberia',
    country: 'Russia',
    category: 'Digital Connectivity',
    priority: 'medium',
    priorityScore: 55.8,
    title: 'Siberian Digital Infrastructure Modernization',
    evidence: [
      '1,900 complaints mostly from rural communities',
      'Broadband penetration 30% below national average',
      'Remote education impacted for 420,000 students',
    ],
    recommendedAction: 'Deploy low-earth-orbit satellite connectivity to 1,200 rural settlements. Upgrade fiber backbone infrastructure in major Siberian cities. Subsidize digital devices for low-income households.',
    expectedImpact: '3.8M rural citizens gain reliable broadband access. Remote education and telemedicine enabled across vast distances.',
    estimatedCost: '₽180 Billion',
    timeframe: '24–48 months',
    confidence: 74,
    affectedPopulation: 3800000,
    aiGenerated: true,
    createdAt: '2024-11-19T00:00:00Z',
  },
];

// ── Government Plans ──────────────────────────────────────────
export const mockGovernmentPlans: GovernmentPlan[] = [
  {
    id: 'GOV-001',
    name: 'Bihar District Healthcare Expansion Phase 2',
    category: 'Healthcare',
    country: 'India',
    regionId: 'REG-001',
    regionName: 'Bihar',
    status: 'planned',
    priority: 'high',
    description: 'Construction of 40 primary health centres and 8 district hospitals across underserved Bihar districts.',
    estimatedBudget: '₹1,800 Crore',
    expectedCompletion: '2026-03-31',
    startDate: '2025-01-01',
    citizenDemandScore: 94,
    governmentInvestmentScore: 42,
    alignmentGap: 52,
    location: { lat: 25.5941, lng: 85.1376 },
    beneficiaries: 5400000,
  },
  {
    id: 'GOV-002',
    name: 'Pradhan Mantri Gram Sadak Yojana — UP Expansion',
    category: 'Roads & Transport',
    country: 'India',
    regionId: 'REG-002',
    regionName: 'Uttar Pradesh',
    status: 'in_progress',
    priority: 'high',
    description: 'Construction and upgrade of 3,200km of rural roads connecting 1,400 villages to main highway network.',
    estimatedBudget: '₹4,200 Crore',
    expectedCompletion: '2025-12-31',
    startDate: '2024-04-01',
    citizenDemandScore: 88,
    governmentInvestmentScore: 62,
    alignmentGap: 26,
    location: { lat: 26.8467, lng: 80.9462 },
    beneficiaries: 8400000,
  },
  {
    id: 'GOV-003',
    name: 'Eastern Cape Water Supply Revitalization',
    category: 'Water & Sanitation',
    country: 'South Africa',
    regionId: 'REG-007',
    regionName: 'Eastern Cape',
    status: 'in_progress',
    priority: 'high',
    description: 'Upgrade of water treatment facilities and expansion of pipe network to rural communities.',
    estimatedBudget: 'R820 Million',
    expectedCompletion: '2025-09-30',
    startDate: '2024-03-01',
    citizenDemandScore: 86,
    governmentInvestmentScore: 58,
    alignmentGap: 28,
    location: { lat: -32.2968, lng: 26.4194 },
    beneficiaries: 1200000,
  },
  {
    id: 'GOV-004',
    name: 'Limpopo Rural Clinics Network',
    category: 'Healthcare',
    country: 'South Africa',
    regionId: 'REG-008',
    regionName: 'Limpopo',
    status: 'planned',
    priority: 'critical',
    description: 'Construction of 30 community clinics and deployment of telemedicine infrastructure.',
    estimatedBudget: 'R1.2 Billion',
    expectedCompletion: '2026-06-30',
    startDate: '2025-04-01',
    citizenDemandScore: 92,
    governmentInvestmentScore: 38,
    alignmentGap: 54,
    location: { lat: -23.4013, lng: 29.4179 },
    beneficiaries: 2100000,
  },
  {
    id: 'GOV-005',
    name: 'Pará Amazon Digital Inclusion Program',
    category: 'Digital Connectivity',
    country: 'Brazil',
    regionId: 'REG-003',
    regionName: 'Pará',
    status: 'planned',
    priority: 'medium',
    description: 'Deployment of satellite internet connectivity to 400 Amazon riverside communities.',
    estimatedBudget: 'R$680 Million',
    expectedCompletion: '2026-12-31',
    startDate: '2025-07-01',
    citizenDemandScore: 74,
    governmentInvestmentScore: 54,
    alignmentGap: 20,
    location: { lat: -3.7172, lng: -52.2271 },
    beneficiaries: 900000,
  },
  {
    id: 'GOV-006',
    name: 'Bihar Solar Rural Electrification',
    category: 'Electricity',
    country: 'India',
    regionId: 'REG-001',
    regionName: 'Bihar',
    status: 'completed',
    priority: 'high',
    description: 'Solar micro-grid deployment providing reliable electricity to 2,800 villages.',
    estimatedBudget: '₹2,100 Crore',
    expectedCompletion: '2024-09-30',
    startDate: '2022-10-01',
    citizenDemandScore: 82,
    governmentInvestmentScore: 78,
    alignmentGap: 4,
    location: { lat: 25.5941, lng: 85.1376 },
    beneficiaries: 6800000,
  },
  {
    id: 'GOV-007',
    name: 'Siberia High-Speed Rail Expansion',
    category: 'Roads & Transport',
    country: 'Russia',
    regionId: 'REG-005',
    regionName: 'Siberia',
    status: 'in_progress',
    priority: 'medium',
    description: 'Extension of Trans-Siberian high speed rail to connect remote Siberian cities.',
    estimatedBudget: '₽420 Billion',
    expectedCompletion: '2027-12-31',
    startDate: '2023-01-01',
    citizenDemandScore: 58,
    governmentInvestmentScore: 84,
    alignmentGap: -26,
    location: { lat: 61.5240, lng: 105.3188 },
    beneficiaries: 4200000,
  },
  {
    id: 'GOV-008',
    name: 'Maranhão Basic Education Infrastructure',
    category: 'Education',
    country: 'Brazil',
    regionId: 'REG-004',
    regionName: 'Maranhão',
    status: 'recommended',
    priority: 'high',
    description: 'AI-recommended: Construction of 180 new schools and teacher training program based on high complaint volume.',
    estimatedBudget: 'R$1.1 Billion',
    expectedCompletion: '2027-03-31',
    startDate: '2025-10-01',
    citizenDemandScore: 84,
    governmentInvestmentScore: 28,
    alignmentGap: 56,
    location: { lat: -4.9609, lng: -45.2744 },
    beneficiaries: 2800000,
  },
];

// ── Analytics ─────────────────────────────────────────────────
export const mockAnalytics: Analytics = {
  complaintsOverTime: [
    { date: 'Jun', complaints: 3200, resolved: 1800, pending: 1400 },
    { date: 'Jul', complaints: 4100, resolved: 2400, pending: 1700 },
    { date: 'Aug', complaints: 3800, resolved: 2200, pending: 1600 },
    { date: 'Sep', complaints: 5200, resolved: 3100, pending: 2100 },
    { date: 'Oct', complaints: 6800, resolved: 4200, pending: 2600 },
    { date: 'Nov', complaints: 8100, resolved: 4900, pending: 3200 },
  ],
  categoryBreakdown: [
    { category: 'Healthcare', count: 9840, percentage: 28.1, trend: 'up' },
    { category: 'Roads & Transport', count: 8620, percentage: 24.6, trend: 'up' },
    { category: 'Water & Sanitation', count: 6130, percentage: 17.5, trend: 'stable' },
    { category: 'Education', count: 4210, percentage: 12.0, trend: 'down' },
    { category: 'Electricity', count: 2940, percentage: 8.4, trend: 'stable' },
    { category: 'Digital Connectivity', count: 2100, percentage: 6.0, trend: 'up' },
    { category: 'Other', count: 1210, percentage: 3.4, trend: 'stable' },
  ],
  regionComparison: [
    { region: 'Bihar', country: 'India', complaints: 8420, resolved: 3900, gapScore: 91, satisfactionScore: 31 },
    { region: 'Uttar Pradesh', country: 'India', complaints: 12100, resolved: 5800, gapScore: 84, satisfactionScore: 38 },
    { region: 'Limpopo', country: 'South Africa', complaints: 3100, resolved: 1300, gapScore: 82, satisfactionScore: 40 },
    { region: 'Pará', country: 'Brazil', complaints: 3200, resolved: 2100, gapScore: 76, satisfactionScore: 54 },
    { region: 'Eastern Cape', country: 'South Africa', complaints: 3500, resolved: 1800, gapScore: 74, satisfactionScore: 46 },
    { region: 'Maranhão', country: 'Brazil', complaints: 2800, resolved: 1400, gapScore: 68, satisfactionScore: 42 },
    { region: 'Siberia', country: 'Russia', complaints: 1900, resolved: 1500, gapScore: 52, satisfactionScore: 61 },
    { region: 'Xinjiang', country: 'China', complaints: 2100, resolved: 1700, gapScore: 48, satisfactionScore: 68 },
  ],
  severityDistribution: [
    { severity: 'Critical (9-10)', count: 4200 },
    { severity: 'High (7-8)', count: 8900 },
    { severity: 'Medium (5-6)', count: 11200 },
    { severity: 'Low (1-4)', count: 10700 },
  ],
  resolutionTime: [
    { category: 'Digital Connectivity', avgDays: 12 },
    { category: 'Education', avgDays: 18 },
    { category: 'Electricity', avgDays: 21 },
    { category: 'Water & Sanitation', avgDays: 28 },
    { category: 'Roads & Transport', avgDays: 35 },
    { category: 'Healthcare', avgDays: 42 },
  ],
};

// ── Dashboard Overview ─────────────────────────────────────────
export const mockDashboardOverview: DashboardOverview = {
  totalComplaints: 35050,
  highPriorityIssues: 8240,
  resolutionRate: 54,
  infrastructureGapIndex: 72,
  citizenSatisfaction: 46,
  activeHotspots: 8,
  countriesConnected: 5,
  complaintsChange: 18.4,
  resolutionChange: 6.2,
};

// ── Citizen Dashboard ──────────────────────────────────────────
export const mockCitizenDashboard: CitizenDashboard = {
  citizenId: 'CTZ-001',
  name: 'Rajesh Kumar',
  region: 'Patna',
  country: 'India',
  myComplaints: 4,
  resolved: 1,
  inProgress: 2,
  areaIssues: 420,
  recentComplaints: mockComplaints.filter(c => c.citizenId === 'CTZ-001'),
  areaOverview: {
    topIssue: 'Healthcare',
    totalComplaints: 420,
    infrastructureGapScore: 91,
    satisfactionScore: 31,
  },
};

// ── Area Data ──────────────────────────────────────────────────
export const mockAreaData: AreaData = {
  region: mockRegions[0],
  issueBreakdown: [
    { category: 'Healthcare', percentage: 42, count: 180 },
    { category: 'Roads', percentage: 31, count: 130 },
    { category: 'Water', percentage: 18, count: 78 },
    { category: 'Education', percentage: 9, count: 32 },
  ],
  nearbyComplaints: [
    {
      id: 'NEAR-001',
      citizenId: 'anon',
      text: 'Healthcare centre closed — no medicines available',
      category: 'Healthcare',
      severity: 8,
      priority: 'high',
      status: 'submitted',
      location: { lat: 25.5960, lng: 85.1400, region: 'Patna', country: 'India' },
      createdAt: '2024-11-17T09:00:00Z',
      updatedAt: '2024-11-17T09:00:00Z',
      timeline: [],
    },
    {
      id: 'NEAR-002',
      citizenId: 'anon',
      text: 'Main road has 20+ potholes causing accidents',
      category: 'Roads & Transport',
      severity: 7,
      priority: 'high',
      status: 'under_review',
      location: { lat: 25.5900, lng: 85.1350, region: 'Patna', country: 'India' },
      createdAt: '2024-11-15T14:00:00Z',
      updatedAt: '2024-11-16T10:00:00Z',
      timeline: [],
    },
    {
      id: 'NEAR-003',
      citizenId: 'anon',
      text: 'Water pipe broken for 3 weeks',
      category: 'Water & Sanitation',
      severity: 6,
      priority: 'medium',
      status: 'in_progress',
      location: { lat: 25.5850, lng: 85.1250, region: 'Patna', country: 'India' },
      createdAt: '2024-11-10T07:00:00Z',
      updatedAt: '2024-11-18T11:00:00Z',
      timeline: [],
    },
  ],
  infrastructureGaps: mockInfrastructureGaps.slice(0, 4),
  governmentPlans: mockGovernmentPlans.filter(p => p.regionId === 'REG-001'),
};
